<div class="content">
    <?php View::content() ?>
    <h3>Menus</h3>
    <ul>
    <?php foreach ($listMenus->items as $item) : ?>
    <li>
        <?= Html::linkAction("edit/$item->id/", 'Editar') ?>
        <?= Html::linkAction("del/$item->id/", 'Borrar') ?>
        <strong><?= $item->nombre ?> - <?= $item->titulo ?></strong>
    </li>
    <?php endforeach ?>
    </ul>
 
     <!-- ejemplo manual de paginador, hay partial listos en formato digg, clasic,.... -->
    <?php if($listMenus->prev) echo Html::linkAction("index/$listMenus->prev/", '<< Anterior |') ?>
    <?php if($listMenus->next) echo Html::linkAction("index/$listMenus->next/", 'Próximo >>') ?>
</div>