
  


<!DOCTYPE html>
<html lang="en">

<head>

  <title>KumbiaPHP Framework</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="">
    <meta name="author" content="">
    <title>Agenda Medica</title>

    <?php Tag::css('kumbia') ?>

  	 
<?php

  	echo Tag::js('js/jquery');
    echo Tag::js('js/tether.min');
    echo Tag::js('js/bootstrap.min');
    //echo Tag::css('login') 
?>
<?php Tag::css('cale/fullcalendar.min'); ?>
<?php //Tag::css('cale/fullcalendar.print.min'); ?>

   <?php 
    echo Tag::js('lib/moment.min');
    echo Tag::js('lib/jquery.min');
    echo Tag::js('lib/jquery-ui.min');


    echo Tag::js('fullcalendar.min');
   ?>
  
    <?php Tag::css('css/bootstrap.min') ?>
    <?php Tag::css('css/heroic-features') ?>
    <?php Tag::css('css/bootstrap.min') ?>
  	<?= Html::includeCss() ?>


     <style>
    .navbar-toggler {
        z-index: 1;
    }
    
    @media (max-width: 576px) {
        nav > .container {
            width: 100%;
        }
    }
    </style>


    <script language="JavaScript">
function aviso(url){
if (!confirm("ALERTA!! va a proceder a eliminar este registro, si desea eliminarlo de click en ACEPTAR\n de lo contrario de click en CANCELAR.")) {
return false;
}
else {
document.location = url;
return true;
}
}
</script>



</head>

<body>

        

    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-toggleable-md navbar-inverse bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarExample" aria-controls="navbarExample" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="container">
            <a class="navbar-brand" href="#">Agenda Medica</a>
            <div class="collapse navbar-collapse" id="navbarExample">
               
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">



            <?php  
            if(Auth::is_valid()){
            echo Html::link('index/inicio/2017-04-06','Citas wer',$attrs ="class='nav-link'"); 
            }


            ?>
                        
                    </li>
                    <li class="nav-item">
            <?php  
            if(Auth::is_valid()){
            echo Html::link('Citas/Index2','Citas',$attrs ="class='nav-link'"); 
            }           
            ?>
                    </li>
                    <li class="nav-item">
            <?php  
            if(Auth::is_valid()){
            echo Html::link('Paciente','Paciente',$attrs ="class='nav-link'"); 
            }           
            ?>
            
                    </li>
                

                </ul>
                
            </div>
        </div>
    </nav>









    <!-- Page Content -->
    <div class="container">
    
        <div class="col-lg-12 col-md-6 mb-4">
        
            
  			<?php View::content() ?>


        </div>    
    </div>
   
    
    <div class="container">
            <div class="row">
                <div class="col-lg-12 paginacion">

                Copyright © Agenda MediK,2017 
                <br>
                Desarrollado por
                <br>
                Marcos Alberto Saavedra
                <br>
                lizeth Nayibe Martinez Sanchez
                </div>
            </div>    

    </div>
   

<?php
  




?>
</body>

</html>





