


    <?php echo Tag::js('login'); ?>
    <?php echo Tag::css('login') ?>

<div class="container">
        <div class="card card-container">
            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
            <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
            <p id="profile-name" class="profile-name-card"></p>
<?php View::content(); ?> 
            <!--
            -->
            
                <?php echo Form::open(); ?>
                <span id="reauth-email" class="reauth-email"></span>
<!--
                <input type="correo" id="correo" class="form-control" placeholder="Email address" required autofocus>
                -->
                <?php echo Form::email("correo",$attrs='type="email" id="email" class="form-control" value="" placeholder="Email address" required autofocus'); ?>
                <br>
                    <!--          
                <input type="password" id="contrasena" class="form-control" placeholder="Password" required>
                -->
                <?php echo Form::pass("contrasena",$attrs='type="password" id="contrasena" class="form-control" placeholder="Password" required'); ?>
                    <br>        
                            <!--   
                <div id="remember" class="checkbox">
                    <label>
                        <input type="checkbox" value="remember-me"> Remember me
                    </label>
                </div>
                -->

                <?php echo Form::submit("Ingresar",$attrs='class="btn btn-lg btn-primary btn-block btn-signin"'); ?>

            <!--
                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in
                </button>
             /form -->
             <br>
            <a href="#" class="forgot-password">
                Forgot the password?
            </a>
        </div><!-- /card-container -->
    </div><!-- /container -->










<?php// echo Form::open(); ?>
<?php// echo Form::label("correo","correo"); ?>
<?php// echo Form::text("correo"); ?>
<?php// echo Form::label("contrasena","contrasena"); ?>
<?php// echo Form::pass("contrasena"); ?>
<?php// echo Form::submit("Ingresar"); ?>
<?php// echo Form::close(); ?>